export interface SubMenuItem {
  label: string
  path: string
}

export interface MenuCategory {
  label: string
  icon: string
  items: SubMenuItem[]
}

export const menuData: MenuCategory[] = [
  {
    label: "Front Office",
    icon: "Phone",
    items: [
      { label: "Admission Enquiry", path: "/admin/front-office/admission-enquiry" },
      { label: "Visitor Book", path: "/admin/front-office/visitor-book" },
      { label: "Phone Call Log", path: "/admin/front-office/phone-call-log" },
      { label: "Postal Dispatch", path: "/admin/front-office/postal-dispatch" },
      { label: "Postal Receive", path: "/admin/front-office/postal-receive" },
      { label: "Complain", path: "/admin/front-office/complain" },
      { label: "Setup Front Office", path: "/admin/front-office/setup" },
    ],
  },
  {
    label: "Student Information",
    icon: "Users",
    items: [
      { label: "Student Details", path: "/admin/student-information/student-details" },
      { label: "Student Admission", path: "/admin/student-information/student-admission" },
      { label: "Online Admission", path: "/admin/student-information/online-admission" },
      { label: "Disabled Students", path: "/admin/student-information/disabled-students" },
      { label: "Multi Class Student", path: "/admin/student-information/multi-class-student" },
      { label: "Bulk Delete", path: "/admin/student-information/bulk-delete" },
      { label: "Student Categories", path: "/admin/student-information/student-categories" },
      { label: "Student House", path: "/admin/student-information/student-house" },
      { label: "Disable Reason", path: "/admin/student-information/disable-reason" },
    ],
  },
  {
    label: "Students Inventory",
    icon: "Package",
    items: [
      { label: "Dashboard", path: "/admin/students-inventory" },
      { label: "Product Master", path: "/admin/students-inventory/products" },
      { label: "Booklist", path: "/admin/students-inventory/books" },
      { label: "Masters", path: "/admin/students-inventory/masters" },
      { label: "Purchases", path: "/admin/students-inventory/purchases" },
      { label: "Stock Management", path: "/admin/students-inventory/stock-management" },
      { label: "Student Sales", path: "/admin/students-inventory/student-sales" },
      { label: "Sales List", path: "/admin/students-inventory/sales-list" },
      { label: "Student Ledger", path: "/admin/students-inventory/student-ledger" },
      { label: "Reports", path: "/admin/students-inventory/reports" },
    ],
  },
  {
    label: "Fees Collection",
    icon: "Wallet",
    items: [
      { label: "Collect Fees", path: "/admin/fees-collection/collect-fees" },
      { label: "Offline Bank Payments", path: "/admin/fees-collection/offline-bank-payments" },
      { label: "Search Fees Payment", path: "/admin/fees-collection/search-fees-payment" },
      { label: "Search Due Fees", path: "/admin/fees-collection/search-due-fees" },
      { label: "Fees Master", path: "/admin/fees-collection/fees-master" },
      { label: "Quick Fees", path: "/admin/fees-collection/quick-fees" },
      { label: "Fees Group", path: "/admin/fees-collection/fees-group" },
      { label: "Fees Type", path: "/admin/fees-collection/fees-type" },
      { label: "Fees Discount", path: "/admin/fees-collection/fees-discount" },
      { label: "Fees Carry Forward", path: "/admin/fees-collection/fees-carry-forward" },
      { label: "Fees Reminder", path: "/admin/fees-collection/fees-reminder" },
      { label: "Payment Change Log", path: "/admin/fees-collection/payment-change-log" },
    ],
  },
  {
    label: "Online Course",
    icon: "BookOpen",
    items: [
      { label: "Online Course", path: "/admin/online-course" },
      { label: "Question Bank", path: "/admin/online-course/question-bank" },
      { label: "Offline Payment", path: "/admin/online-course/offline-payment" },
      { label: "Course Category", path: "/admin/online-course/course-category" },
      { label: "Certificate Template", path: "/admin/online-course/certificate-template" },
      { label: "Online Course Report", path: "/admin/online-course/report" },
      { label: "Setting", path: "/admin/online-course/setting" },
    ],
  },
  {
    label: "Behaviour Records",
    icon: "ShieldAlert",
    items: [
      { label: "Assign Incident", path: "/admin/behaviour-records/assign-incident" },
      { label: "Incidents", path: "/admin/behaviour-records/incidents" },
      { label: "Reports", path: "/admin/behaviour-records/reports" },
      { label: "Setting", path: "/admin/behaviour-records/setting" },
    ],
  },
  {
    label: "Multi Branch",
    icon: "GitBranch",
    items: [
      { label: "Overview", path: "/admin/multi-branch/overview" },
      { label: "Report", path: "/admin/multi-branch/report" },
      { label: "Setting", path: "/admin/multi-branch/setting" },
    ],
  },
  {
    label: "Gmeet Live Classes",
    icon: "Video",
    items: [
      { label: "Live Classes", path: "/admin/gmeet-live-classes/live-classes" },
      { label: "Live Meeting", path: "/admin/gmeet-live-classes/live-meeting" },
      { label: "Live Classes Report", path: "/admin/gmeet-live-classes/live-classes-report" },
      { label: "Live Meeting Report", path: "/admin/gmeet-live-classes/live-meeting-report" },
      { label: "Setting", path: "/admin/gmeet-live-classes/setting" },
    ],
  },
  {
    label: "Zoom Live Classes",
    icon: "Camera",
    items: [
      { label: "Live Meeting", path: "/admin/zoom-live-classes/live-meeting" },
      { label: "Live Classes", path: "/admin/zoom-live-classes/live-classes" },
      { label: "Live Classes Report", path: "/admin/zoom-live-classes/live-classes-report" },
      { label: "Live Meeting Report", path: "/admin/zoom-live-classes/live-meeting-report" },
      { label: "Setting", path: "/admin/zoom-live-classes/setting" },
    ],
  },
  {
    label: "Income",
    icon: "TrendingUp",
    items: [
      { label: "Add Income", path: "/admin/income/add-income" },
      { label: "Search Income", path: "/admin/income/search-income" },
      { label: "Income Head", path: "/admin/income/income-head" },
    ],
  },
  {
    label: "Expenses",
    icon: "TrendingDown",
    items: [
      { label: "Add Expense", path: "/admin/expenses/add-expense" },
      { label: "Search Expense", path: "/admin/expenses/search-expense" },
      { label: "Expense Head", path: "/admin/expenses/expense-head" },
    ],
  },
  {
    label: "QR Code Attendance",
    icon: "QrCode",
    items: [
      { label: "Attendance", path: "/admin/qr-code-attendance/attendance" },
      { label: "Setting", path: "/admin/qr-code-attendance/setting" },
    ],
  },
  {
    label: "CBSE Examination",
    icon: "ClipboardCheck",
    items: [
      { label: "Exam", path: "/admin/cbse-examination/exam" },
      { label: "Exam Schedule", path: "/admin/cbse-examination/exam-schedule" },
      { label: "Print Marksheet", path: "/admin/cbse-examination/print-marksheet" },
      { label: "Template", path: "/admin/cbse-examination/template" },
      { label: "Assign Observation", path: "/admin/cbse-examination/assign-observation" },
      { label: "Admit Card", path: "/admin/cbse-examination/admit-card" },
      { label: "Reports", path: "/admin/cbse-examination/reports" },
      { label: "Setting", path: "/admin/cbse-examination/setting" },
    ],
  },
  {
    label: "ICSE Examination",
    icon: "Award",
    items: [
      { label: "Exam", path: "/admin/icse-examination/exam" },
      { label: "Exam Schedule", path: "/admin/icse-examination/exam-schedule" },
      { label: "Print Marksheet", path: "/admin/icse-examination/print-marksheet" },
      { label: "Template", path: "/admin/icse-examination/template" },
      { label: "Assign Observation", path: "/admin/icse-examination/assign-observation" },
      { label: "Admit Card", path: "/admin/icse-examination/admit-card" },
      { label: "Reports", path: "/admin/icse-examination/reports" },
      { label: "Setting", path: "/admin/icse-examination/setting" },
      { label: "Custom Marksheet Entry", path: "/admin/icse-examination/custom-marksheet-entry" },
      { label: "Custom Marksheet", path: "/admin/icse-examination/custom-marksheet" },
    ],
  },
  {
    label: "Examinations",
    icon: "FileText",
    items: [
      { label: "Custom Result", path: "/admin/examinations" },
      { label: "Exam Group", path: "/admin/examinations/exam-group" },
      { label: "Exam Schedule", path: "/admin/examinations/exam-schedule" },
      { label: "Exam Result", path: "/admin/examinations/exam-result" },
      { label: "Design Admit Card", path: "/admin/examinations/design-admit-card" },
      { label: "Print Admit Card", path: "/admin/examinations/print-admit-card" },
      { label: "Design Marksheet", path: "/admin/examinations/design-marksheet" },
      { label: "Print Marksheet", path: "/admin/examinations/print-marksheet" },
      { label: "Marks Grade", path: "/admin/examinations/marks-grade" },
      { label: "Marks Division", path: "/admin/examinations/marks-division" },
    ],
  },
  {
    label: "Attendance",
    icon: "ClipboardList",
    items: [
      { label: "Student Attendance", path: "/admin/attendance/student-attendance" },
      { label: "Approve Leave", path: "/admin/attendance/approve-leave" },
      { label: "Attendance By Date", path: "/admin/attendance/attendance-by-date" },
    ],
  },
  {
    label: "Online Examinations",
    icon: "Monitor",
    items: [
      { label: "Online Exam", path: "/admin/online-examinations/online-exam" },
      { label: "Question Bank", path: "/admin/online-examinations/question-bank" },
    ],
  },
  {
    label: "Academics",
    icon: "GraduationCap",
    items: [
      { label: "Class Timetable", path: "/admin/academics/class-timetable" },
      { label: "Teachers Timetable", path: "/admin/academics/teachers-timetable" },
      { label: "Assign Class Teacher", path: "/admin/academics/assign-class-teacher" },
      { label: "Promote Students", path: "/admin/academics/promote-students" },
      { label: "Subject Group", path: "/admin/academics/subject-group" },
      { label: "Subjects", path: "/admin/academics/subjects" },
      { label: "Class & Section", path: "/admin/academics/class" },
    ],
  },
  {
    label: "Annual Calendar",
    icon: "Calendar",
    items: [
      { label: "Annual Calendar", path: "/admin/annual-calendar" },
      { label: "Holiday Type", path: "/admin/annual-calendar/holiday-type" },
    ],
  },
  {
    label: "Lesson Plan",
    icon: "BookTemplate",
    items: [
      { label: "Copy Old Lessons", path: "/admin/lesson-plan/copy-old-lessons" },
      { label: "Manage Lesson Plan", path: "/admin/lesson-plan/manage-lesson-plan" },
      { label: "Manage Syllabus Status", path: "/admin/lesson-plan/manage-syllabus-status" },
      { label: "Lesson", path: "/admin/lesson-plan/lesson" },
      { label: "Topic", path: "/admin/lesson-plan/topic" },
    ],
  },
  {
    label: "Human Resource",
    icon: "Briefcase",
    items: [
      { label: "Staff Directory", path: "/admin/human-resource/staff-directory" },
      { label: "Staff Attendance", path: "/admin/human-resource/staff-attendance" },
      { label: "Payroll", path: "/admin/human-resource/payroll" },
      { label: "Approve Leave Request", path: "/admin/human-resource/approve-leave-request" },
      { label: "Apply Leave", path: "/admin/human-resource/apply-leave" },
      { label: "Leave Type", path: "/admin/human-resource/leave-type" },
      { label: "Teachers Rating", path: "/admin/human-resource/teachers-rating" },
      { label: "Department", path: "/admin/human-resource/department" },
      { label: "Designation", path: "/admin/human-resource/designation" },
      { label: "Disabled Staff", path: "/admin/human-resource/disabled-staff" },
    ],
  },
  {
    label: "Communicate",
    icon: "MessageSquare",
    items: [
      { label: "Notice Board", path: "/admin/communicate/notice-board" },
      { label: "Send Email", path: "/admin/communicate/send-email" },
      { label: "Send SMS", path: "/admin/communicate/send-sms" },
      { label: "Email / SMS Log", path: "/admin/communicate/email-sms-log" },
      { label: "Schedule Email SMS Log", path: "/admin/communicate/schedule-email-sms-log" },
      { label: "Login Credentials Send", path: "/admin/communicate/login-credentials-send" },
      { label: "Email Template", path: "/admin/communicate/email-template" },
      { label: "SMS Template", path: "/admin/communicate/sms-template" },
    ],
  },
  {
    label: "Download Center",
    icon: "Download",
    items: [
      { label: "Upload/Share Content", path: "/admin/download-center/upload-share-content" },
      { label: "Content Share List", path: "/admin/download-center/content-share-list" },
      { label: "Video Tutorial", path: "/admin/download-center/video-tutorial" },
      { label: "Content Type", path: "/admin/download-center/content-type" },
    ],
  },
  {
    label: "Homework",
    icon: "BookCopy",
    items: [
      { label: "Add Homework", path: "/admin/homework/add-homework" },
      { label: "Daily Assignment", path: "/admin/homework/daily-assignment" },
    ],
  },
  {
    label: "Library",
    icon: "Library",
    items: [
      { label: "Book List", path: "/admin/library/book-list" },
      { label: "Book Requests", path: "/admin/library/book-requests" },
      { label: "Issue - Return", path: "/admin/library/issue-return" },
      { label: "Members", path: "/admin/library/members" },
      { label: "Add Student", path: "/admin/library/add-student" },
      { label: "Add Staff Member", path: "/admin/library/add-staff-member" },
    ],
  },
  {
    label: "Staff Inventory",
    icon: "Package",
    items: [
      { label: "Inventory", path: "/admin/staff-inventory" },
      { label: "Issue Item", path: "/admin/staff-inventory/issue-item" },
      { label: "Add Item Stock", path: "/admin/staff-inventory/add-item-stock" },
      { label: "Add Item", path: "/admin/staff-inventory/add-item" },
      { label: "Item Category", path: "/admin/staff-inventory/item-category" },
      { label: "Item Store", path: "/admin/staff-inventory/item-store" },
      { label: "Item Supplier", path: "/admin/staff-inventory/item-supplier" },
    ],
  },
  {
    label: "Student CV",
    icon: "FileUser",
    items: [
      { label: "Build CV", path: "/admin/student-cv/build-cv" },
      { label: "Download CV", path: "/admin/student-cv/download-cv" },
      { label: "Fees Master", path: "/admin/student-cv/fees-master" },
    ],
  },
  {
    label: "Transport",
    icon: "Bus",
    items: [
      { label: "Pickup Point", path: "/admin/transport/pickup-point" },
      { label: "Routes", path: "/admin/transport/routes" },
      { label: "Vehicles", path: "/admin/transport/vehicles" },
      { label: "Assign Vehicle", path: "/admin/transport/assign-vehicle" },
      { label: "Route Pickup Point", path: "/admin/transport/route-pickup-point" },
      { label: "Student Transport Fees", path: "/admin/transport/student-transport-fees" },
    ],
  },
  {
    label: "Hostel",
    icon: "Building2",
    items: [
      { label: "Hostel Rooms", path: "/admin/hostel/hostel-rooms" },
      { label: "Room Type", path: "/admin/hostel/room-type" },
      { label: "Hostel", path: "/admin/hostel/hostel" },
    ],
  },
  {
    label: "Certificate",
    icon: "Award",
    items: [
      { label: "Transfer Certificate", path: "/admin/certificate/transfer-certificate" },
      { label: "Student Certificate", path: "/admin/certificate/student-certificate" },
      { label: "Generate Certificate", path: "/admin/certificate/generate-certificate" },
      { label: "Student ID Card", path: "/admin/certificate/student-id-card" },
      { label: "Generate ID Card", path: "/admin/certificate/generate-id-card" },
      { label: "Staff ID Card", path: "/admin/certificate/staff-id-card" },
      { label: "Generate Staff ID Card", path: "/admin/certificate/generate-staff-id-card" },
    ],
  },
  {
    label: "Custom Result",
    icon: "Award",
    items: [
      { label: "Primary Format (Class I to V)", path: "/admin/result-card/templates" },
      { label: "Enter / Import Results", path: "/admin/result-card/records" },
      { label: "Print Result Cards", path: "/admin/result-card/print" },
    ],
  },
  {
    label: "Front CMS",
    icon: "Layout",
    items: [
      { label: "Event", path: "/admin/front-cms/event" },
      { label: "Gallery", path: "/admin/front-cms/gallery" },
      { label: "News", path: "/admin/front-cms/news" },
      { label: "Media Manager", path: "/admin/front-cms/media-manager" },
      { label: "Pages", path: "/admin/front-cms/pages" },
      { label: "Menus", path: "/admin/front-cms/menus" },
      { label: "Banner Images", path: "/admin/front-cms/banner-images" },
    ],
  },
  {
    label: "Alumni",
    icon: "UserCheck",
    items: [
      { label: "Manage Alumni", path: "/admin/alumni/manage-alumni" },
      { label: "Events", path: "/admin/alumni/events" },
      { label: "Student Information", path: "/admin/alumni/student-information" },
      { label: "Finance", path: "/admin/alumni/finance" },
      { label: "Attendance", path: "/admin/alumni/attendance" },
      { label: "Examinations", path: "/admin/alumni/examinations" },
      { label: "Online Examinations", path: "/admin/alumni/online-examinations" },
      { label: "Lesson Plan", path: "/admin/alumni/lesson-plan" },
      { label: "Human Resource", path: "/admin/alumni/human-resource" },
      { label: "Homework", path: "/admin/alumni/homework" },
      { label: "Library", path: "/admin/alumni/library" },
      { label: "Inventory", path: "/admin/alumni/inventory" },
      { label: "Transport", path: "/admin/alumni/transport" },
      { label: "Hostel", path: "/admin/alumni/hostel" },
    ],
  },
  {
    label: "Reports",
    icon: "BarChart3",
    items: [
      { label: "All Reports", path: "/admin/reports" },
      { label: "Student Report", path: "/admin/reports/student-report" },
      { label: "Attendance Report", path: "/admin/reports/attendance-report" },
      { label: "Fees Collection Report", path: "/admin/reports/fees-collection-report" },
      { label: "Staff Report", path: "/admin/reports/staff-report" },
      { label: "User Log", path: "/admin/reports/user-log" },
      { label: "Audit Trail Report", path: "/admin/reports/audit-trail-report" },
    ],
  },
  {
    label: "Rest API",
    icon: "GitBranch",
    items: [
      { label: "API Docs", path: "/admin/multi-branch/rest-api" },
    ],
  },
  {
    label: "AI Hub",
    icon: "Sparkles",
    items: [
      { label: "AI Hub", path: "/admin/ai-hub" },
    ],
  },
  {
    label: "System Setting",
    icon: "Settings",
    items: [
      { label: "General Setting", path: "/admin/system-setting/general-setting" },
      { label: "Front CMS Setting", path: "/admin/system-setting/front-cms-setting" },
      { label: "Users & Permissions", path: "/admin/system-setting/users-permission" },
      { label: "Modules", path: "/admin/system-setting/modules" },
      { label: "Student Profile Update", path: "/admin/system-setting/student-profile-update" },
      { label: "Online Admission", path: "/admin/system-setting/online-admission" },
      { label: "System Update", path: "/admin/system-setting/system-update" },
    ],
  },
  {
    label: "Subscription",
    icon: "CreditCard",
    items: [
      { label: "Subscription & Billing", path: "/admin/subscription" },
    ],
  },
]
